import { AcIcon, KitchenIcon, ParkingIcon, WifiIcon } from "@/components/icons";
import type { Room } from "@/types/room";

const amenities = [
  { icon: WifiIcon, label: "Wifi" },
  { icon: KitchenIcon, label: "Cocina" },
  { icon: ParkingIcon, label: "Estacionamiento" },
  { icon: AcIcon, label: "Aire acondicionado" },
];

export const mockRooms: Room[] = [
  {
    id: "1",
    title: "Cabaña acogedora en el bosque",
    subtitle: "Cabaña entera · Monteverde",
    category: "Cabañas",
    imageUrl: "https://picsum.photos/seed/cabana-bosque/600/400",
    pricePerNight: 45000,
    originalPrice: 55000,
    rating: 4.9,
    reviewCount: 128,
    isFavoriteBadge: true,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    photos: [
      "https://loremflickr.com/600/400/cabin,forest?lock=1",
      "https://loremflickr.com/600/400/cabin,forest,bedroom?lock=11",
      "https://loremflickr.com/600/400/cabin,forest,kitchen?lock=21",
    ],
    guestCount: 4,
    host: {
      name: "Sofía",
      avatarUrl: "https://i.pravatar.cc/150?img=32",
      yearsHosting: 4,
    },
    amenities,
  },
  {
    id: "2",
    title: "Apartamento moderno en el centro",
    subtitle: "Apartamento entero · San José",
    category: "Vistas",
    imageUrl: "https://picsum.photos/seed/apartamento-centro/600/400",
    pricePerNight: 38000,
    rating: 4.7,
    reviewCount: 64,
    isFreeCancellation: true,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    photos: [
      "https://loremflickr.com/600/400/apartment,interior?lock=2",
      "https://loremflickr.com/600/400/apartment,interior,bedroom?lock=12",
      "https://loremflickr.com/600/400/apartment,interior,kitchen?lock=22",
    ],
    guestCount: 2,
    host: {
      name: "Diego",
      avatarUrl: "https://i.pravatar.cc/150?img=12",
      yearsHosting: 2,
    },
    amenities: [amenities[0], amenities[1], amenities[3]],
  },
  {
    id: "3",
    title: "Casa con vista a la montaña",
    subtitle: "Casa entera · Turrialba",
    category: "Vistas",
    imageUrl: "https://picsum.photos/seed/casa-montana/600/400",
    pricePerNight: 62000,
    photos: [
      "https://loremflickr.com/600/400/house,mountain?lock=3",
      "https://loremflickr.com/600/400/house,mountain,bedroom?lock=13",
      "https://loremflickr.com/600/400/house,mountain,kitchen?lock=23",
    ],
    guestCount: 6,
    host: {
      name: "Valeria",
      avatarUrl: "https://i.pravatar.cc/150?img=47",
      yearsHosting: 6,
    },
    amenities,
  },
  {
    id: "4",
    title: "Loft minimalista cerca de la playa",
    subtitle: "Loft entero · Jacó",
    category: "Playa",
    imageUrl: "https://picsum.photos/seed/loft-playa/600/400",
    pricePerNight: 51000,
    rating: 4.5,
    reviewCount: 37,
    isFreeCancellation: true,
    photos: [
      "https://loremflickr.com/600/400/loft,beach?lock=4",
      "https://loremflickr.com/600/400/loft,beach,bedroom?lock=14",
      "https://loremflickr.com/600/400/loft,beach,kitchen?lock=24",
    ],
    guestCount: 2,
    host: {
      name: "Andrés",
      avatarUrl: "https://i.pravatar.cc/150?img=15",
      yearsHosting: 3,
    },
    amenities: [amenities[0], amenities[1], amenities[3]],
  },
  {
    id: "5",
    title: "Habitación privada en casa familiar",
    subtitle: "Habitación privada · Heredia",
    category: "Cabañas",
    imageUrl: "https://picsum.photos/seed/habitacion-familiar/600/400",
    pricePerNight: 22000,
    photos: [
      "https://loremflickr.com/600/400/bedroom,house?lock=5",
      "https://loremflickr.com/600/400/bedroom,house,bedroom?lock=15",
      "https://loremflickr.com/600/400/bedroom,house,kitchen?lock=25",
    ],
    guestCount: 1,
    host: {
      name: "Mariana",
      avatarUrl: "https://i.pravatar.cc/150?img=25",
      yearsHosting: 5,
    },
    amenities: [amenities[0], amenities[3]],
  },
  {
    id: "6",
    title: "Villa espaciosa con piscina",
    subtitle: "Casa entera · Guanacaste",
    category: "Piscina",
    imageUrl: "https://picsum.photos/seed/villa-piscina/600/400",
    pricePerNight: 98000,
    originalPrice: 120000,
    isFavoriteBadge: true,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    photos: [
      "https://loremflickr.com/600/400/villa,pool?lock=6",
      "https://loremflickr.com/600/400/villa,pool,bedroom?lock=16",
      "https://loremflickr.com/600/400/villa,pool,kitchen?lock=26",
    ],
    guestCount: 10,
    host: {
      name: "Roberto",
      avatarUrl: "https://i.pravatar.cc/150?img=53",
      yearsHosting: 8,
    },
    amenities,
  },
];