import type { Listing } from "@/types/listing";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Cabaña acogedora en el bosque",
    subtitle: "Cabaña entera · Monteverde",
    category: "Cabañas",
    imageUrl: "https://loremflickr.com/600/400/cabin,forest?lock=1",
    pricePerNight: 45000,
    originalPrice: 55000,
    rating: 4.9,
    reviewCount: 128,
    isFavoriteBadge: true,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
  },
  {
    id: "2",
    title: "Apartamento moderno en el centro",
    subtitle: "Apartamento entero · San José",
    category: "Vistas",
    imageUrl: "https://loremflickr.com/600/400/apartment,interior?lock=2",
    pricePerNight: 38000,
    rating: 4.7,
    reviewCount: 64,
    isFreeCancellation: true,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    id: "3",
    title: "Casa con vista a la montaña",
    subtitle: "Casa entera · Turrialba",
    category: "Vistas",
    imageUrl: "https://loremflickr.com/600/400/house,mountain?lock=3",
    pricePerNight: 62000,
  },
  {
    id: "4",
    title: "Loft minimalista cerca de la playa",
    subtitle: "Loft entero · Jacó",
    category: "Playa",
    imageUrl: "https://loremflickr.com/600/400/loft,beach?lock=4",
    pricePerNight: 51000,
    rating: 4.5,
    reviewCount: 37,
    isFreeCancellation: true,
  },
  {
    id: "5",
    title: "Habitación privada en casa familiar",
    subtitle: "Habitación privada · Heredia",
    category: "Cabañas",
    imageUrl: "https://loremflickr.com/600/400/bedroom,house?lock=5",
    pricePerNight: 22000,
  },
  {
    id: "6",
    title: "Villa espaciosa con piscina",
    subtitle: "Casa entera · Guanacaste",
    category: "Piscina",
    imageUrl: "https://loremflickr.com/600/400/villa,pool?lock=6",
    pricePerNight: 98000,
    originalPrice: 120000,
    isFavoriteBadge: true,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
  },
];
